name             'metadata-service-cb'
maintainer       'Code-Playground'
maintainer_email 'daniel.harlea@gmail.com'
license          'All rights reserved'
description      'Installs/Configures metadata-service-cb'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'apt'
depends 'git'
depends 'apache2'
depends 'java'
depends 'maven'
depends 'openssl'
depends 'tomcat'